--Под SYS!!!


CREATE OR REPLACE CONTEXT IBSOBJID USING SET_IBSOBJID_VALUE;

CREATE OR REPLACE PROCEDURE SET_IBSOBJID_VALUE (
  par IN VARCHAR2
, val IN VARCHAR2 
) 
AS
BEGIN DBMS_SESSION.SET_CONTEXT ( 'IBSOBJID', par, val );
END;
/

GRANT EXECUTE ON SET_IBSOBJID_VALUE TO public;
